# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [ ]:
2 + 2

4

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [ ]:
import numpy as np

In [ ]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [ ]:
vec.dtype

dtype('int64')

In [ ]:
type(vec)

numpy.ndarray

Размер массива:

In [ ]:
vec.shape

(3, 2)

Число осей:

In [ ]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [ ]:
np.sum(vec)

21

In [ ]:
np.sum(vec, axis=0)

array([ 9, 12])

In [ ]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [ ]:
vec.sum()

21

Транспонируем массив:

In [ ]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [ ]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [ ]:
vec[:, 1]

array([2, 4, 6])

In [ ]:
vec[2, :]

array([5, 6])

In [ ]:
vec[1:2, 0]

array([3])

In [ ]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [ ]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [ ]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [ ]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [ ]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [ ]:
vec.dot(vec**2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [ ]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [ ]:
vec + np.arange(3).reshape(3, 1)

Булевы массивы:

In [ ]:
is_even = vec % 2 == 0
print(is_even)

In [ ]:
np.sum(is_even)

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [ ]:
vec[vec % 2 == 0]

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [ ]:
np.zeros((2, 3))

Массив из единиц:

In [ ]:
np.ones((3, 2))

Единичная матрица:

In [ ]:
np.identity(5)

Массивы можно объединять:

In [ ]:
vec

In [ ]:
np.hstack((vec, np.zeros(vec.shape)))

In [ ]:
np.vstack((vec, np.zeros(vec.shape)))

Генерация случайных чисел:

In [ ]:
np.random.rand(2, 3)

In [ ]:
np.random.seed(2019)
np.random.rand(2, 3)

In [ ]:
np.random.randn(3, 2)

In [ ]:
np.random.normal(2, 1, size=3)

In [ ]:
np.random.randint(5, 10, size=3)

Почему вообще используют `numpy`?

In [ ]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [ ]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

In [ ]:
%%time
C = A @ B

### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

#1

In [ ]:
a = np.array([3,5,2,7,8,3])
np.flip(a)

array([3, 8, 7, 2, 5, 3])

#2

In [ ]:
a = np.array([2, 1, 4, 10,3,9,12])
np.max(a[a % 2 == 1])

9

#3

In [ ]:
a = np.array([2, 1, 4, 10,3,9,12])
a[a % 2 == 1] = 2
a

array([ 2,  2,  4, 10,  2,  2, 12])

#4

In [ ]:
n = int(input())
np.arange(2 * n - 1, 0, -2)

3


array([5, 3, 1])

#5

In [ ]:
a = np.array([0, 1, 2, 3, 4])
number = 1.33
(a[np.argmin(np.abs(a - number))], a[np.argmax(np.abs(a - number))])

(1, 4)

#6

In [ ]:
a = np.array([4, 6, 0, 1])
b = a / np.arange(a.size, 0, -1)
b = np.append(b, -2)
b

array([ 1.,  2.,  0.,  1., -2.])

#7

In [ ]:
a = np.array([4, 6, 0, 1])
a = a[:-1]
a = a * np.arange(a.size, 0, -1)
x = 10
x_arr = np.full((1, a.size), x)
x_arr = x_arr ** np.arange(x_arr.size, 0, -1)
np.sum(a * x_arr)

13200